set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_seg[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_seg[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_seg[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_seg[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_seg[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_seg[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_seg[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_seg[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_selc[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_selc[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {edd_selc[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports edd_en]
set_property PACKAGE_PIN H19 [get_ports {edd_seg[7]}]
set_property PACKAGE_PIN G20 [get_ports {edd_seg[6]}]
set_property PACKAGE_PIN J22 [get_ports {edd_seg[5]}]
set_property PACKAGE_PIN K22 [get_ports {edd_seg[4]}]
set_property PACKAGE_PIN K21 [get_ports {edd_seg[3]}]
set_property PACKAGE_PIN H20 [get_ports {edd_seg[2]}]
set_property PACKAGE_PIN H22 [get_ports {edd_seg[1]}]
set_property PACKAGE_PIN J21 [get_ports {edd_seg[0]}]

set_property PACKAGE_PIN M22 [get_ports {edd_selc[2]}]
set_property PACKAGE_PIN M21 [get_ports {edd_selc[1]}]
set_property PACKAGE_PIN N22 [get_ports {edd_selc[0]}]
set_property PACKAGE_PIN H4 [get_ports clk]
set_property PACKAGE_PIN L21 [get_ports edd_en]

set_property DRIVE 12 [get_ports {edd_seg[7]}]
set_property DRIVE 12 [get_ports {edd_seg[6]}]
set_property DRIVE 12 [get_ports {edd_seg[5]}]
set_property DRIVE 12 [get_ports {edd_seg[4]}]
set_property DRIVE 12 [get_ports {edd_seg[3]}]
set_property DRIVE 12 [get_ports {edd_seg[2]}]
set_property DRIVE 12 [get_ports {edd_seg[1]}]
set_property DRIVE 12 [get_ports {edd_seg[0]}]

set_property PACKAGE_PIN T3 [get_ports sw]
set_property IOSTANDARD LVCMOS18 [get_ports sw]
set_property PULLTYPE PULLDOWN [get_ports sw]

set_property IOSTANDARD LVCMOS18 [get_ports {in_dig[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in_dig[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in_dig[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {in_dig[0]}]
set_property PACKAGE_PIN R6 [get_ports {in_dig[3]}]
set_property PACKAGE_PIN U7 [get_ports {in_dig[2]}]
set_property PACKAGE_PIN AB7 [get_ports {in_dig[1]}]
set_property PACKAGE_PIN AB8 [get_ports {in_dig[0]}]
set_property PULLTYPE PULLDOWN [get_ports {in_dig[3]}]
set_property PULLTYPE PULLDOWN [get_ports {in_dig[2]}]
set_property PULLTYPE PULLDOWN [get_ports {in_dig[1]}]
set_property PULLTYPE PULLDOWN [get_ports {in_dig[0]}]
